insert into public.foods (
  name,
  brand,
  serving_label,
  serving_grams,
  calories,
  protein_g,
  carbs_g,
  fat_g,
  fiber_g,
  is_public,
  slug,
  source,
  default_servings,
  sodium_mg,
  keywords,
  suggested_meal_ids,
  featured_in_barcode_preview
)
values
  ('Scrambled Eggs', null, '1 egg', null, 93, 6, 1, 5, 0, true, 'scrambled-eggs', 'usda', 2, 90, ARRAY['eggs', 'breakfast', 'protein']::text[], ARRAY['breakfast']::text[], false),
  ('My Morning Oats', 'Saved Meal', '1 bowl', null, 205, 12, 36, 4, 5, true, 'morning-oats', 'saved', 1, 160, ARRAY['oats', 'overnight oats', 'breakfast']::text[], ARRAY['breakfast']::text[], false),
  ('Grilled Chicken Bowl', 'Recipe', '1 bowl', null, 289, 34, 28, 8, 4, true, 'grilled-chicken-bowl', 'recipe', 1, 540, ARRAY['chicken bowl', 'rice bowl', 'lunch']::text[], ARRAY['lunch', 'dinner']::text[], false),
  ('Salmon Plate', 'Recipe', '1 plate', null, 395, 30, 18, 16, 3, true, 'salmon-plate', 'recipe', 1, 420, ARRAY['salmon', 'dinner', 'omega']::text[], ARRAY['dinner']::text[], false),
  ('Greek Yogurt', null, '1 cup', null, 160, 15, 12, 3, 0, true, 'greek-yogurt', 'usda', 1, 68, ARRAY['yogurt', 'snack', 'protein']::text[], ARRAY['breakfast', 'snacks']::text[], false),
  ('Gold Standard Whey', 'Optimum Nutrition', '1 shake', null, 190, 28, 8, 5, 1, true, 'protein-shake', 'nutritionix', 1, 140, ARRAY['protein shake', 'whey', 'post workout']::text[], ARRAY['snacks', 'breakfast']::text[], true),
  ('Turkey Wrap', 'Recipe', '1 wrap', null, 330, 26, 30, 10, 4, true, 'turkey-wrap', 'recipe', 1, 620, ARRAY['turkey', 'wrap', 'lunch']::text[], ARRAY['lunch']::text[], false),
  ('Tuna Sandwich', 'Recipe', '1 sandwich', null, 310, 27, 27, 9, 3, true, 'tuna-sandwich', 'recipe', 1, 560, ARRAY['tuna', 'sandwich', 'lunch']::text[], ARRAY['lunch']::text[], false),
  ('Chicken Rice Prep', 'Saved Meal', '1 container', null, 360, 32, 34, 8, 3, true, 'rice-chicken-plate', 'saved', 1, 470, ARRAY['meal prep', 'chicken rice', 'prep']::text[], ARRAY['lunch', 'dinner']::text[], false),
  ('Peanut Butter Toast', null, '1 slice', null, 220, 9, 18, 12, 3, true, 'peanut-butter-toast', 'usda', 1, 210, ARRAY['toast', 'peanut butter', 'breakfast']::text[], ARRAY['breakfast', 'snacks']::text[], false),
  ('Fruit Cup', null, '1 cup', null, 120, 2, 27, 0, 3, true, 'fruit-cup', 'usda', 1, 2, ARRAY['fruit', 'snack', 'banana']::text[], ARRAY['breakfast', 'snacks']::text[], false),
  ('Greek Yogurt Parfait', 'Recipe', '1 cup', null, 210, 14, 20, 6, 2, true, 'greek-yogurt-parfait', 'recipe', 1, 115, ARRAY['parfait', 'yogurt', 'berries']::text[], ARRAY['breakfast', 'snacks']::text[], false),
  ('Chicken Breast', null, '120 g', null, 165, 31, 0, 4, 0, true, 'chicken-breast', 'usda', 1, 74, ARRAY['chicken', 'lean protein']::text[], ARRAY['lunch', 'dinner']::text[], false),
  ('White Rice', null, '1 cup', null, 206, 4, 45, 0, 1, true, 'white-rice', 'usda', 1, 2, ARRAY['rice', 'carbs', 'side']::text[], ARRAY['lunch', 'dinner']::text[], false),
  ('Banana', null, '1 banana', null, 105, 1, 27, 0, 3, true, 'banana', 'usda', 1, 1, ARRAY['banana', 'fruit', 'pre workout']::text[], ARRAY['breakfast', 'snacks']::text[], false),
  ('Chocolate Protein Bar', 'Quest', '1 bar', null, 200, 20, 22, 7, 14, true, 'protein-bar', 'nutritionix', 1, 210, ARRAY['protein bar', 'chocolate', 'snack']::text[], ARRAY['snacks']::text[], true),
  ('Lemon Lime Sports Drink', 'Gatorade', '1 bottle', null, 140, 0, 36, 0, 0, true, 'sports-drink', 'nutritionix', 1, 270, ARRAY['gatorade', 'sports drink', 'hydration']::text[], ARRAY['snacks']::text[], true),
  ('Strawberry Yogurt Cup', 'Chobani', '1 cup', null, 150, 11, 16, 3, 0, true, 'greek-yogurt-cup', 'nutritionix', 1, 75, ARRAY['chobani', 'yogurt', 'snack']::text[], ARRAY['snacks', 'breakfast']::text[], true),
  ('Post-Workout Combo', 'Saved Meal', '1 set', null, 350, 33, 40, 5, 5, true, 'post-workout-combo', 'saved', 1, 310, ARRAY['post workout', 'protein', 'carbs']::text[], ARRAY['snacks', 'dinner']::text[], false)
on conflict (slug) do update
set
  name = excluded.name,
  brand = excluded.brand,
  serving_label = excluded.serving_label,
  serving_grams = excluded.serving_grams,
  calories = excluded.calories,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  is_public = excluded.is_public,
  source = excluded.source,
  default_servings = excluded.default_servings,
  sodium_mg = excluded.sodium_mg,
  keywords = excluded.keywords,
  suggested_meal_ids = excluded.suggested_meal_ids,
  featured_in_barcode_preview = excluded.featured_in_barcode_preview;
